"""``performance.seating`` — regenerate vox-deorum ``seating.json`` cycle files.

For each *incomplete* controlled experiment, produce a ``<experiment>.seating.json``
that mirrors the vox-deorum game runner's on-disk cycle schema, with already-played
``(seating_rotation, seed)`` slots marked ``completed`` and the missing ones left
**open** (absent = pending). Dropping such a file into the runner's configs dir makes
it schedule exactly the missing games and then stop.

Everything here is derived from civ-bench's own extracted data (the controlled
strength panel + the games table): this module **never reads any vox-deorum config or
state file** — it only *replicates the format*. The runner's loader keeps a provided
file's cells (so it plays only the open ones) iff the header
``(totalSeats, seedCount, seatingSeed, sorted configSlots)`` and the
``basePerm``/``consumeOrder`` lengths match what it computes from its config; all of
those are reconstructed from the data here. ``seatingSeed`` is the one field absent
from civ-bench data — it is emitted as ``0`` (correct for ``randomizeSeating`` in
``{true, 0, false}``) and the assumption is flagged inline in each file's ``_comment``.
"""

from __future__ import annotations

import json

import pandas as pd

from .strength_panel import _controlled_panel, _ordered_game_ids, _reference_slots

# Not in civ-bench data; correct for ``randomizeSeating`` in {true, 0, false}. Flagged
# in each file's ``_comment`` so an operator can adjust for a nonzero numeric seed.
ASSUMED_SEATING_SEED = 0

SEATING_INDEX_COLUMNS = [
    "experiment", "file", "total_cells", "completed_cells", "open_cells",
]


def _comment(experiment: str) -> str:
    return (
        f"Generated by civ-bench performance.experiment_completeness for experiment "
        f"'{experiment}' from extracted game data. 'completed' cells are games already "
        f"present in the analyzed dataset; absent cells are OPEN (to be played). "
        f"seatingSeed is assumed 0 — verify/adjust if the source config used a nonzero "
        f"numeric randomizeSeating. basePerm/consumeOrder order is arbitrary (only the "
        f"set of open games matters)."
    )


def _config_slots(exp_df: pd.DataFrame) -> list[int]:
    """The pre-rotation configured slots (vox-deorum ``llmPlayers`` keys) for one experiment."""
    if "config_slot" not in exp_df.columns:
        return []
    slots = exp_df["config_slot"].dropna()
    return sorted({int(s) for s in slots if int(s) != -1})


def _present_slots(exp_df: pd.DataFrame, games: pd.DataFrame | None) -> dict[tuple[int, int], str]:
    """Map each present ``(seating_rotation, seed)`` slot to its keep-candidate game id.

    Keep-candidate = earliest game by timestamp (mirrors ``build_experiment_completeness``'s
    repeated-slot ordering) so a regenerated ``completed`` cell is deterministic.
    """
    present: dict[tuple[int, int], str] = {}
    for (seed, rot), ids in exp_df.groupby(["seed", "seating_rotation"], sort=True)["game_id"]:
        ordered = _ordered_game_ids(ids.dropna().astype(str).unique().tolist(), games)
        if ordered:
            present[(int(rot), int(seed))] = ordered[0]
    return present


def build_seating_state(
    experiment: str,
    total_seats: int,
    config_slots: list[int],
    design_seeds: list[int],
    present: dict[tuple[int, int], str],
) -> dict:
    """Assemble the vox-deorum ``seating.json`` schema for one experiment.

    ``present`` maps ``(seating_rotation, seed) -> game_id`` for games already in the
    dataset; cells absent from it are omitted (= pending = open). ``design_seeds`` is
    the sorted design seed set — a seed's index in it is its ``seedIndex``.
    """
    seed_count = len(design_seeds)
    seed_to_index = {int(seed): idx for idx, seed in enumerate(design_seeds)}
    cells: dict[str, dict[str, dict]] = {}
    for (rotation, seed), game_id in present.items():
        idx = seed_to_index.get(int(seed))
        if idx is None or not (0 <= int(rotation) < total_seats):
            continue
        cells.setdefault(str(int(rotation)), {})[str(idx)] = {
            "status": "completed",
            "gameID": str(game_id),
        }
    consume_order = [
        {"rotation": r, "seedIndex": s}
        for r in range(total_seats)
        for s in range(seed_count)
    ]
    return {
        "_comment": _comment(experiment),
        "totalSeats": int(total_seats),
        "configSlots": [int(s) for s in config_slots],
        "seedCount": int(seed_count),
        "seatingSeed": ASSUMED_SEATING_SEED,
        "basePerm": list(range(int(total_seats))),
        "consumeOrder": consume_order,
        "cells": cells,
        "completedCycles": 0,
    }


def validate_seating_state(state: dict) -> list[str]:
    """Check ``state`` against vox-deorum's acceptance + scheduler invariants.

    Returns human-readable problems; an empty list means the runner's ``loadOrInit``
    will keep the file as-is (not rebuild → not replay completed games) and its
    ``pickCell`` can reach every open cell. Mirrors
    ``io.ts loadOrInit`` (header + ``basePerm``/``consumeOrder`` lengths) and the
    ``cells.ts`` scheduler requirement that every ``(rotation, seedIndex)`` appears in
    ``consumeOrder`` exactly once.
    """
    problems: list[str] = []
    ts = state.get("totalSeats")
    sc = state.get("seedCount")
    if not isinstance(ts, int) or isinstance(ts, bool) or ts <= 0:
        return [f"totalSeats must be a positive int, got {ts!r}"]
    if not isinstance(sc, int) or isinstance(sc, bool) or sc < 1:
        return [f"seedCount must be an int >= 1, got {sc!r}"]

    slots = state.get("configSlots")
    if not isinstance(slots, list) or not slots or any(
        not isinstance(s, int) or isinstance(s, bool) for s in slots
    ):
        problems.append(f"configSlots must be a non-empty int list, got {slots!r}")
    else:
        if slots != sorted(slots) or len(set(slots)) != len(slots):
            problems.append(f"configSlots must be strictly ascending & unique, got {slots}")
        if any(s < 0 or s >= ts for s in slots):
            problems.append(f"configSlots out of range [0,{ts}): {slots}")

    seed = state.get("seatingSeed")
    if not isinstance(seed, int) or isinstance(seed, bool) or seed < 0:
        problems.append(f"seatingSeed must be a non-negative int, got {seed!r}")

    base = state.get("basePerm")
    if not isinstance(base, list) or sorted(base) != list(range(ts)):
        problems.append(f"basePerm must be a permutation of 0..{ts - 1}, got {base!r}")

    order = state.get("consumeOrder")
    expected = {(r, s) for r in range(ts) for s in range(sc)}
    if not isinstance(order, list):
        problems.append("consumeOrder must be a list")
    else:
        seen = [(c.get("rotation"), c.get("seedIndex")) for c in order]
        if len(seen) != ts * sc:
            problems.append(f"consumeOrder must have {ts * sc} entries, got {len(seen)}")
        if set(seen) != expected or len(set(seen)) != len(seen):
            problems.append("consumeOrder must list every (rotation, seedIndex) exactly once")

    cells = state.get("cells")
    if not isinstance(cells, dict):
        problems.append("cells must be an object")
    else:
        for rk, inner in cells.items():
            if not str(rk).lstrip("-").isdigit() or not (0 <= int(rk) < ts) or not isinstance(inner, dict):
                problems.append(f"cells['{rk}'] out of range / not an object")
                continue
            for sk, entry in inner.items():
                if not str(sk).lstrip("-").isdigit() or not (0 <= int(sk) < sc):
                    problems.append(f"cells['{rk}']['{sk}'] seedIndex out of range")
                elif entry.get("status") == "completed" and not entry.get("gameID"):
                    problems.append(f"completed cell ({rk},{sk}) is missing a gameID")

    if not isinstance(state.get("completedCycles"), int) or isinstance(state.get("completedCycles"), bool):
        problems.append("completedCycles must be an int")
    return problems


def generate_seating_files(
    panel: pd.DataFrame,
    games: pd.DataFrame | None = None,
    baseline_experiment: str | None = None,
) -> tuple[dict[str, str], list[dict], list[str]]:
    """Build ``seating/<exp>.seating.json`` text per *incomplete* controlled experiment.

    Returns ``(artifacts, index_rows, warnings)``: ``artifacts`` maps the artifact path
    (relative to the analysis dir) to the JSON text, ``index_rows`` feed the
    ``seating_index`` summary table, and ``warnings`` are non-fatal notes.
    """
    artifacts: dict[str, str] = {}
    index_rows: list[dict] = []
    warnings: list[str] = []

    controlled = _controlled_panel(panel)
    if controlled.empty:
        return artifacts, index_rows, warnings

    design_seeds = sorted({int(seed) for seed, _ in _reference_slots(controlled, baseline_experiment)})
    if not design_seeds:
        return artifacts, index_rows, warnings
    design_seed_set = set(design_seeds)

    for experiment, exp_df in controlled.groupby("experiment", sort=True):
        config_slots = _config_slots(exp_df)
        if not config_slots:
            warnings.append(
                f"seating '{experiment}': no configured slots (config_slot all -1) — skipped."
            )
            continue
        total_seats = max(config_slots) + 1

        bad_rot = sorted({int(r) for r in exp_df["seating_rotation"].unique() if int(r) >= total_seats})
        if bad_rot:
            warnings.append(
                f"seating '{experiment}': seating_rotation(s) {bad_rot} >= totalSeats "
                f"{total_seats}; those games are omitted from the cycle."
            )
        unknown_seeds = sorted({int(s) for s in exp_df["seed"].unique()} - design_seed_set)
        if unknown_seeds:
            warnings.append(
                f"seating '{experiment}': seed(s) {unknown_seeds} not in the design seed "
                f"set {design_seeds}; those games are omitted from the cycle."
            )

        present = {
            (rot, seed): gid
            for (rot, seed), gid in _present_slots(exp_df, games).items()
            if rot < total_seats and seed in design_seed_set
        }
        total_cells = total_seats * len(design_seeds)
        completed_cells = len(present)
        open_cells = total_cells - completed_cells
        if open_cells <= 0:
            continue  # complete (or over-complete) — nothing to open

        state = build_seating_state(experiment, total_seats, config_slots, design_seeds, present)
        problems = validate_seating_state(state)
        if problems:
            # Never ship a structurally-unconsumable file; by construction this is
            # unreachable, so it's a guard that locks the invariant.
            warnings.append(
                f"seating '{experiment}': not emitted (invalid: {'; '.join(problems)})."
            )
            continue
        rel = f"seating/{experiment}.seating.json"
        artifacts[rel] = json.dumps(state, indent=2)
        index_rows.append({
            "experiment": experiment,
            "file": rel,
            "total_cells": int(total_cells),
            "completed_cells": int(completed_cells),
            "open_cells": int(open_cells),
        })

    return artifacts, index_rows, warnings
