"""Report templates: assemble produced :class:`Section`s into a document (stage 5).

A *template* is a pure function ``(meta, sections) -> ReportDocument``. It decides
structure only — grouping, ordering, headings, intro prose — never *which*
analyses ran (that is the run-spec's job) and never an analysis's own content
(that is the module's job). The shipped ``default`` template groups sections into
the five analysis families (ratings / prediction / calibration / performance /
exploratory), preserving the dependency order the runner resolved, so no analysis
hardcodes its place in the document (invariant 3).

Register a new template by adding it to :data:`TEMPLATES`; the run-spec selects it
by ``report.template`` (default ``"default"``).
"""

from __future__ import annotations

from typing import Callable

from .errors import ReportError
from .model import FamilyGroup, ReportDocument, Section

# Friendly titles for the known module families; an unknown family falls back to
# a title-cased version of its registry prefix (so a future family renders too).
_FAMILY_TITLES = {
    "ratings": "Ratings",
    "prediction": "Prediction",
    "calibration": "Calibration",
    "performance": "Performance",
    "exploratory": "Exploratory",
}

# Stable display order for the families; unknown families sort after these, in the
# order they first appear among the sections.
_FAMILY_ORDER = ["ratings", "prediction", "calibration", "performance", "exploratory"]


def family_of(module: str) -> str:
    """The family key of a ``family.module`` registry name (``"ratings"``)."""
    return module.split(".", 1)[0] if "." in module else module


def family_title(key: str) -> str:
    return _FAMILY_TITLES.get(key, key.replace("_", " ").title())


def family_sort_index(key: str) -> int:
    """Canonical position of a family (unknown families sort last). The runner uses
    this to order the *default* (``sections:null``) document; explicit
    ``report.sections`` keep their authored order instead."""
    return _FAMILY_ORDER.index(key) if key in _FAMILY_ORDER else len(_FAMILY_ORDER)


def _group_by_family(sections: list[Section]) -> list[FamilyGroup]:
    """Bucket sections into family groups, preserving the incoming section order
    both within a group and across groups (groups appear in first-appearance order).

    Ordering is therefore the runner's responsibility: the default path hands us
    sections already sorted into canonical family order, while an explicit
    ``report.sections`` list hands us the author's exact order — either way we keep
    it (invariant 3: the template never reorders behind the config's back)."""
    groups: dict[str, FamilyGroup] = {}
    order: list[str] = []
    for section in sections:
        key = family_of(section.module)
        if key not in groups:
            groups[key] = FamilyGroup(key=key, title=family_title(key))
            order.append(key)
        groups[key].sections.append(section)
    return [groups[k] for k in order]


def default_template(meta: dict, sections: list[Section]) -> ReportDocument:
    """The default report layout: family chapters in dependency order."""
    groups = _group_by_family(sections)
    n = len(sections)
    intro = (
        f"Benchmark report for run **{meta['run_name']}** "
        f"(seed {meta['seed']}). "
        f"Generated by `civ-bench` from `{meta['config_path']}` — "
        f"{n} analysis section(s) grouped into {len(groups)} "
        f"{'family' if len(groups) == 1 else 'families'} "
        f"(members in config order within each family). "
        f"Every section is regenerated from the pipeline's analysis artifacts; "
        f"nothing in this document is hand-authored."
    )
    section_by_id = {section.id: section for section in sections}
    overview_sections = [
        section_by_id[section_id]
        for section_id in meta.get("overview_section_ids", [])
        if section_id in section_by_id
    ]
    return ReportDocument(
        title=meta["title"],
        run_name=meta["run_name"],
        seed=meta["seed"],
        config_path=meta["config_path"],
        output_root=meta["output_root"],
        groups=groups,
        overview_sections=overview_sections,
        intro=intro,
    )


TEMPLATES: dict[str, Callable[[dict, list[Section]], ReportDocument]] = {
    "default": default_template,
}


def get_template(name: str) -> Callable[[dict, list[Section]], ReportDocument]:
    if name not in TEMPLATES:
        raise ReportError(
            f"unknown report template '{name}'. Available: {sorted(TEMPLATES)}."
        )
    return TEMPLATES[name]
